name: Daily Update

on:
  schedule:
    - cron:  '0 12 */1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run task
      run: |
        python update_snippets.py
        python build_data.py

    - name: Commit files
      run: |
        DATE=`date +%Y-%m-%d`
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -a -m ":arrow_up: Daily update at $DATE"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
